# Generated by Django 4.2.16 on 2026-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_userstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='freeze_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
