# Generated by Django 4.2.16 on 2026-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_userstreak_freeze_count_userstreak_longest_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tutorial_completed',
            field=models.BooleanField(default=False),
        ),
    ]
