# Generated by Django 4.2.16 on 2026-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=20)),
                ('min_supported_version', models.CharField(max_length=20)),
                ('force_update_message', models.TextField(default='Please update the app to continue.')),
            ],
        ),
    ]
