# Generated by Django 4.2.16 on 2026-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingfeature',
            constraint=models.UniqueConstraint(fields=('user', 'package_name', 'notification_key', 'feature_version'), name='unique_training_feature'),
        ),
    ]
