# Generated by Django 4.2.16 on 2026-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_trainingfeature_unique_training_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfeature',
            name='original_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
