# Generated by Django 4.2.16 on 2026-02-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(db_index=True, max_length=255)),
                ('app_label', models.CharField(blank=True, default='', max_length=255)),
                ('icon_reference', models.CharField(blank=True, default='', help_text='URL or path to app icon, not binary data', max_length=512)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_key', models.CharField(db_index=True, max_length=256)),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(default='general', max_length=50)),
                ('post_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('big_text', models.TextField(blank=True, null=True)),
                ('sub_text', models.CharField(blank=True, max_length=500, null=True)),
                ('summary_text', models.CharField(blank=True, max_length=500, null=True)),
                ('info_text', models.CharField(blank=True, max_length=500, null=True)),
                ('text_lines', models.TextField(blank=True, help_text='JSON array of text lines', null=True)),
                ('large_icon_base64', models.TextField(blank=True, null=True)),
                ('picture_base64', models.TextField(blank=True, null=True)),
                ('conversation_title', models.CharField(blank=True, max_length=500, null=True)),
                ('people', models.TextField(blank=True, help_text='JSON array of contact names/IDs', null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of content for deduplication', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='Notifications.app')),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CLICK', 'Click'), ('SWIPE', 'Swipe'), ('EXPAND', 'Expand'), ('APP_CANCEL', 'App Cancel'), ('OTHER', 'Other')], max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_reason', models.IntegerField(blank=True, help_text='Android NotificationListenerService removal reason code', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Flexible JSON storage for event-specific data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='Notifications.notificationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction Event',
                'verbose_name_plural': 'Interaction Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('posts', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('swipes', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='Notifications.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Aggregate',
                'verbose_name_plural': 'Daily Aggregates',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='For future snooze feature', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('ml_score', models.FloatField(blank=True, db_index=True, help_text='Cached ML ranking score', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='Notifications.notificationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification State',
                'verbose_name_plural': 'User Notification States',
                'indexes': [models.Index(fields=['user', 'is_read', 'ml_score'], name='Notificatio_user_id_a86e29_idx'), models.Index(fields=['user', 'opened_at'], name='Notificatio_user_id_5f8320_idx'), models.Index(fields=['notification_event', 'user'], name='Notificatio_notific_6891ff_idx')],
                'unique_together': {('user', 'notification_event')},
            },
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
                ('notification_event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Notifications.notificationevent')),
            ],
            options={
                'verbose_name': 'Notification Message',
                'verbose_name_plural': 'Notification Messages',
                'indexes': [models.Index(fields=['notification_event', 'message_time'], name='Notificatio_notific_a572f2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['app', 'post_time'], name='Notificatio_app_id_f2640e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['app', 'notif_key'], name='Notificatio_app_id_277e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['post_time'], name='Notificatio_post_ti_b5b41f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationevent',
            unique_together={('app', 'notif_key')},
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'timestamp'], name='Notificatio_user_id_cdf040_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['notification_event', 'timestamp'], name='Notificatio_notific_3f6c71_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'interaction_type', 'timestamp'], name='Notificatio_user_id_e09856_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['user', 'day'], name='Notificatio_user_id_9d3b70_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['app', 'day'], name='Notificatio_app_id_5bb072_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['day'], name='Notificatio_day_1fa365_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together={('user', 'app', 'day')},
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['user', 'package_name'], name='Notificatio_user_id_c02e2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('user', 'package_name')},
        ),
    ]
