# Generated by Django 4.2.16 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_usernotificationstate_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationstate',
            name='dismissed_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('notifybear', 'NotifyBear'), ('app', 'App')], db_index=True, help_text='Who dismissed the notification', max_length=20, null=True),
        ),
    ]
