# Generated by Django 4.2.16 on 2025-12-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notifications', '0002_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('app_label', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('posts', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('swipes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_key', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('removed_at', models.DateTimeField(db_index=True)),
                ('raw_reason', models.IntegerField(blank=True, null=True)),
                ('interaction_type', models.CharField(choices=[('CLICK', 'Click'), ('SWIPE', 'Swipe'), ('APP_CANCEL', 'App cancel'), ('OTHER', 'Other')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_key',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'package_name'], name='Notificatio_user_id_74efb1_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'post_time'], name='Notificatio_user_id_c41645_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['package_name', 'post_time'], name='Notificatio_package_8ed8ab_idx'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='Notifications.app'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='Notifications.app'),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'removed_at'], name='Notificatio_user_id_d61950_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['app', 'removed_at'], name='Notificatio_app_id_61450a_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'notif_key'], name='Notificatio_user_id_5ad6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['user', 'day'], name='Notificatio_user_id_9d3b70_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['app', 'day'], name='Notificatio_app_id_5bb072_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together={('user', 'app', 'day')},
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['user', 'package_name'], name='Notificatio_user_id_c02e2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('user', 'package_name')},
        ),
    ]
