# Generated by Django 5.1.1 on 2025-12-28 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_app_dailyaggregate_interactionevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_key', models.CharField(db_index=True, max_length=256)),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('post_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('big_text', models.TextField(blank=True, null=True)),
                ('sub_text', models.CharField(blank=True, max_length=500, null=True)),
                ('summary_text', models.CharField(blank=True, max_length=500, null=True)),
                ('info_text', models.CharField(blank=True, max_length=500, null=True)),
                ('text_lines', models.TextField(blank=True, help_text='JSON array of text lines', null=True)),
                ('large_icon_base64', models.TextField(blank=True, null=True)),
                ('picture_base64', models.TextField(blank=True, null=True)),
                ('conversation_title', models.CharField(blank=True, max_length=500, null=True)),
                ('people', models.TextField(blank=True, help_text='JSON array of contact names/IDs', null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of content for deduplication', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='For future snooze feature', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('ml_score', models.FloatField(blank=True, db_index=True, help_text='Cached ML ranking score', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Notification State',
                'verbose_name_plural': 'User Notification States',
            },
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='notification',
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='dailyaggregate',
            options={'verbose_name': 'Daily Aggregate', 'verbose_name_plural': 'Daily Aggregates'},
        ),
        migrations.AlterModelOptions(
            name='interactionevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Interaction Event', 'verbose_name_plural': 'Interaction Events'},
        ),
        migrations.AlterModelOptions(
            name='notificationmessage',
            options={'verbose_name': 'Notification Message', 'verbose_name_plural': 'Notification Messages'},
        ),
        migrations.RemoveIndex(
            model_name='interactionevent',
            name='Notificatio_user_id_d61950_idx',
        ),
        migrations.RemoveIndex(
            model_name='interactionevent',
            name='Notificatio_app_id_61450a_idx',
        ),
        migrations.RemoveIndex(
            model_name='interactionevent',
            name='Notificatio_user_id_5ad6eb_idx',
        ),
        migrations.RemoveField(
            model_name='interactionevent',
            name='app',
        ),
        migrations.RemoveField(
            model_name='interactionevent',
            name='notif_key',
        ),
        migrations.RemoveField(
            model_name='interactionevent',
            name='removed_at',
        ),
        migrations.AddField(
            model_name='app',
            name='icon_reference',
            field=models.CharField(blank=True, default='', help_text='URL or path to app icon, not binary data', max_length=512),
        ),
        migrations.AddField(
            model_name='app',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='open_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Flexible JSON storage for event-specific data', null=True),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='app',
            name='package_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interactionevent',
            name='interaction_type',
            field=models.CharField(choices=[('CLICK', 'Click'), ('SWIPE', 'Swipe'), ('EXPAND', 'Expand'), ('APP_CANCEL', 'App Cancel'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='interactionevent',
            name='raw_reason',
            field=models.IntegerField(blank=True, help_text='Android NotificationListenerService removal reason code', null=True),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['day'], name='Notificatio_day_1fa365_idx'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='Notifications.app'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='notification_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='Notifications.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='notification_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Notifications.notificationevent'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'timestamp'], name='Notificatio_user_id_cdf040_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['notification_event', 'timestamp'], name='Notificatio_notific_3f6c71_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', 'interaction_type', 'timestamp'], name='Notificatio_user_id_e09856_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmessage',
            index=models.Index(fields=['notification_event', 'message_time'], name='Notificatio_notific_a572f2_idx'),
        ),
        migrations.AddField(
            model_name='usernotificationstate',
            name='notification_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='Notifications.notificationevent'),
        ),
        migrations.AddField(
            model_name='usernotificationstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['app', 'post_time'], name='Notificatio_app_id_f2640e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['app', 'notif_key'], name='Notificatio_app_id_277e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['post_time'], name='Notificatio_post_ti_b5b41f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationevent',
            unique_together={('app', 'notif_key')},
        ),
        migrations.AddIndex(
            model_name='usernotificationstate',
            index=models.Index(fields=['user', 'is_read', 'ml_score'], name='Notificatio_user_id_a86e29_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationstate',
            index=models.Index(fields=['user', 'opened_at'], name='Notificatio_user_id_5f8320_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationstate',
            index=models.Index(fields=['notification_event', 'user'], name='Notificatio_notific_6891ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationstate',
            unique_together={('user', 'notification_event')},
        ),
    ]
