# Generated by Django 4.2.16 on 2026-03-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_usernotificationstate_dismissed_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationevent',
            unique_together={('app', 'notif_key', 'content_hash')},
        ),
    ]
