# Generated by Django 4.2.16 on 2026-03-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0004_alter_notificationevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationstate',
            name='manual_priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
