# Generated by Django 4.2.16 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_usernotificationstate_manual_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationstate',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
